sudo: required
dist: trusty

language: node_js

node_js:
  - "4"
  - "6"
  - "7"

env:
  - SEQUELIZE=^1.0.0
  - SEQUELIZE=^2.0.0
  - SEQUELIZE=^3.0.0

cache:
  directories:
  - $HOME/.yarn-cache

before_install:
  # Repo for newer Node.js versions
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

install:
  - "yarn"

before_script:
  - yarn add sequelize@$(echo $SEQUELIZE)

script:
#  - "npm run lint"
  - "npm run coverage"

after_success: "npm run coveralls"

notifications:
  irc:
    - "chat.freenode.net#sequelizejs"
