sudo: required
dist: trusty

language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "iojs-v1"
  - "iojs-v2"
  - "iojs-v3"
  - "4"
  - "5"

env:
  - SEQUELIZE=^1.0.0
  - SEQUELIZE=^2.0.0
  - SEQUELIZE=^3.0.0

after_success: "npm run coveralls"

before_script:
  - npm install sequelize@$(echo $SEQUELIZE)

script:
  - "npm run lint"
  - "npm run coverage"

notifications:
  irc:
    - "chat.freenode.net#sequelizejs"
