sudo: required
dist: trusty

language: node_js

node_js:
  - "4"
  - "6"
  - "7"

env:
  - SEQUELIZE=^1.0.0
  - SEQUELIZE=^2.0.0
  - SEQUELIZE=^3.0.0

cache:
  directories:
  - $HOME/.yarn-cache

before_install:
  - "npm install -g yarn"

install:
  - "yarn"

before_script:
  - yarn add sequelize@$(echo $SEQUELIZE)

script:
#  - "npm run lint"
  - "npm run coverage"

after_success: "npm run coveralls"

notifications:
  irc:
    - "chat.freenode.net#sequelizejs"
